site_name: python-physics
theme:
  name: material
  palette:
    primary: white
  highlightjs: true
markdown_extensions:
  - pymdownx.arithmatex
extra_css:  
  - https://cdnjs.cloudflare.com/ajax/libs/highlight.js/10.1.1/styles/github.min.css
  - stylesheets/extra.css
extra_javascript:    
  - https://cdnjs.cloudflare.com/ajax/libs/highlight.js/10.1.1/highlight.min.js
  - javascripts/extra.js  
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-AMS-MML_HTMLorMML