site_name: python-physics
theme:
  name: material
  highlightjs: true
markdown_extensions:
  - pymdownx.arithmatex
  - pymdownx.highlight:
      use_pygments: true
  - pymdownx.inlinehilite
extra_javascript: 
    - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-AMS-MML_HTMLorMML
extra_css:
  - stylesheets/extra.css
extra_javascript:
  - javascripts/extra.js
