site_name: python-physics
theme:
  name: material
  highlightjs: true
markdown_extensions:
  - pymdownx.arithmatex
extra_css:
  - stylesheets/extra.css
extra_javascript:  
  - https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js
  - javascripts/highlight.js
  - javascripts/extra.js
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-AMS-MML_HTMLorMML
